language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

before_script:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean build check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "LnEHmq5BKRzXvuWJwOjZsIW0gNTr6d/JT1dOuYLsKYmGQ+0MLbjoB1J1AIpZ5X1qcDDUbPomQ2YDYvi+cavjk6FMccyKxnnC5sqjUgTnkHOnVzteGFP+0TYT3JZnjFrzp6mxNXG2vPeuyIAdDZRTogEOe83nfFRvytj6VGK/seI="
    - secure: "qdCwZom4m109rrqm80N/Q+JTYob5WubDnPVKJlXoMIzh+ppq6XWiqKsBUypzn9sSEVHuYSQAzeUqyp3ET0E/sNyvnOe9cRQEs7aMjYSXw5XUYrsPT10HbAStmqPeGp6X+LuOr+jmfPQyyKeZGBOLq3Trb1yRGlrwMQhE6BFbX8g="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
